image: java:8

stages:
  - test

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

tests:
  stage: test
  variables:
    MYSQL_DATABASE: kwery
    POSTGRES_DB: kwery
    POSTGRES_USER: kwery
    MYSQL_USER: kwery
    MYSQL_ROOT_PASSWORD: kwery
    POSTGRES_PASSWORD: kwery
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  services:
    - postgres
    - mysql
  cache:
    paths:
      - build
      - .gradle
  script:
    - ./gradlew --info check
