version: '3.6'

services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: kwery
      MYSQL_USER: kwery
      MYSQL_PASSWORD: kwery
      MYSQL_ROOT_PASSWORD: kwery
    ports:
      - 3336:3306

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: kwery
      POSTGRES_USER: kwery
      POSTGRES_PASSWORD: kwery
    ports:
      - 5432:5432

  hsqldb:
    image: datagrip/hsqldb:2.3.4
    environment:
      HSQLDB_USER: kwery
    ports:
      - 9001:9001
