version: '3.6'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: kwery
      MYSQL_USER: kwery
      MYSQL_PASSWORD: kwery
      MYSQL_ROOT_PASSWORD: kwery
    ports:
      - 3306:3306

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: kwery
      POSTGRES_USER: kwery
      POSTGRES_PASSWORD: kwery
    ports:
      - 5432:5432
